// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rmvnorm
arma::mat rmvnorm(unsigned int n, const arma::vec& mu, const arma::mat& sigma);
RcppExport SEXP fourPNO_rmvnorm(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    __result = Rcpp::wrap(rmvnorm(n, mu, sigma));
    return __result;
END_RCPP
}
// kappa_initialize
arma::mat kappa_initialize(const arma::vec& Ms);
RcppExport SEXP fourPNO_kappa_initialize(SEXP MsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type Ms(MsSEXP);
    __result = Rcpp::wrap(kappa_initialize(Ms));
    return __result;
END_RCPP
}
// update_theta
Rcpp::List update_theta(unsigned int N, const arma::mat& Z, const arma::vec& as, const arma::vec& bs, arma::vec& theta, const double& mu_theta, const double& Sigma_theta_inv);
RcppExport SEXP fourPNO_update_theta(SEXP NSEXP, SEXP ZSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP thetaSEXP, SEXP mu_thetaSEXP, SEXP Sigma_theta_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu_theta(mu_thetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type Sigma_theta_inv(Sigma_theta_invSEXP);
    __result = Rcpp::wrap(update_theta(N, Z, as, bs, theta, mu_theta, Sigma_theta_inv));
    return __result;
END_RCPP
}
// update_ab_NA
Rcpp::List update_ab_NA(unsigned int N, unsigned int J, const arma::mat& Z, arma::vec& as, arma::vec& bs, const arma::vec& theta, const arma::vec& mu_xi, const arma::mat& Sigma_xi_inv);
RcppExport SEXP fourPNO_update_ab_NA(SEXP NSEXP, SEXP JSEXP, SEXP ZSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP thetaSEXP, SEXP mu_xiSEXP, SEXP Sigma_xi_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_xi(mu_xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_xi_inv(Sigma_xi_invSEXP);
    __result = Rcpp::wrap(update_ab_NA(N, J, Z, as, bs, theta, mu_xi, Sigma_xi_inv));
    return __result;
END_RCPP
}
// update_ab_norestriction
Rcpp::List update_ab_norestriction(unsigned int N, unsigned int J, const arma::mat& Z, arma::vec& as, arma::vec& bs, const arma::vec& theta, const arma::vec& mu_xi, const arma::mat& Sigma_xi_inv);
RcppExport SEXP fourPNO_update_ab_norestriction(SEXP NSEXP, SEXP JSEXP, SEXP ZSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP thetaSEXP, SEXP mu_xiSEXP, SEXP Sigma_xi_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_xi(mu_xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_xi_inv(Sigma_xi_invSEXP);
    __result = Rcpp::wrap(update_ab_norestriction(N, J, Z, as, bs, theta, mu_xi, Sigma_xi_inv));
    return __result;
END_RCPP
}
// update_WKappaZ_NA
Rcpp::List update_WKappaZ_NA(const arma::mat& Y, const arma::vec& Ysum, arma::mat& Z, const arma::vec& as, const arma::vec& bs, const arma::vec& gs, const arma::vec& ss, const arma::vec& theta, const arma::mat& Kaps, double alpha_c, double beta_c, double alpha_s, double beta_s, unsigned int gwg_reps);
RcppExport SEXP fourPNO_update_WKappaZ_NA(SEXP YSEXP, SEXP YsumSEXP, SEXP ZSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP gsSEXP, SEXP ssSEXP, SEXP thetaSEXP, SEXP KapsSEXP, SEXP alpha_cSEXP, SEXP beta_cSEXP, SEXP alpha_sSEXP, SEXP beta_sSEXP, SEXP gwg_repsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Ysum(YsumSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gs(gsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kaps(KapsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_c(alpha_cSEXP);
    Rcpp::traits::input_parameter< double >::type beta_c(beta_cSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_s(alpha_sSEXP);
    Rcpp::traits::input_parameter< double >::type beta_s(beta_sSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type gwg_reps(gwg_repsSEXP);
    __result = Rcpp::wrap(update_WKappaZ_NA(Y, Ysum, Z, as, bs, gs, ss, theta, Kaps, alpha_c, beta_c, alpha_s, beta_s, gwg_reps));
    return __result;
END_RCPP
}
// min2LL_4pno
double min2LL_4pno(unsigned int N, unsigned int J, const arma::mat& Y, const arma::vec& as, const arma::vec& bs, const arma::vec& gs, const arma::vec& ss, const arma::vec& theta);
RcppExport SEXP fourPNO_min2LL_4pno(SEXP NSEXP, SEXP JSEXP, SEXP YSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP gsSEXP, SEXP ssSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gs(gsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    __result = Rcpp::wrap(min2LL_4pno(N, J, Y, as, bs, gs, ss, theta));
    return __result;
END_RCPP
}
// Y_4pno_simulate
arma::mat Y_4pno_simulate(unsigned int N, unsigned int J, const arma::vec& as, const arma::vec& bs, const arma::vec& gs, const arma::vec& ss, const arma::vec& theta);
RcppExport SEXP fourPNO_Y_4pno_simulate(SEXP NSEXP, SEXP JSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP gsSEXP, SEXP ssSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gs(gsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    __result = Rcpp::wrap(Y_4pno_simulate(N, J, as, bs, gs, ss, theta));
    return __result;
END_RCPP
}
// Total_Tabulate
arma::uvec Total_Tabulate(unsigned int N, unsigned int J, const arma::mat Y);
RcppExport SEXP fourPNO_Total_Tabulate(SEXP NSEXP, SEXP JSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Y(YSEXP);
    __result = Rcpp::wrap(Total_Tabulate(N, J, Y));
    return __result;
END_RCPP
}
// Gibbs_4PNO
Rcpp::List Gibbs_4PNO(const arma::mat& Y, const arma::vec& mu_xi, const arma::mat& Sigma_xi_inv, const double& mu_theta, const double& Sigma_theta_inv, double alpha_c, double beta_c, double alpha_s, double beta_s, unsigned int burnin, const arma::vec& cTF, const arma::vec& sTF, unsigned int gwg_reps, unsigned int chain_length);
RcppExport SEXP fourPNO_Gibbs_4PNO(SEXP YSEXP, SEXP mu_xiSEXP, SEXP Sigma_xi_invSEXP, SEXP mu_thetaSEXP, SEXP Sigma_theta_invSEXP, SEXP alpha_cSEXP, SEXP beta_cSEXP, SEXP alpha_sSEXP, SEXP beta_sSEXP, SEXP burninSEXP, SEXP cTFSEXP, SEXP sTFSEXP, SEXP gwg_repsSEXP, SEXP chain_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_xi(mu_xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_xi_inv(Sigma_xi_invSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu_theta(mu_thetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type Sigma_theta_inv(Sigma_theta_invSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_c(alpha_cSEXP);
    Rcpp::traits::input_parameter< double >::type beta_c(beta_cSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_s(alpha_sSEXP);
    Rcpp::traits::input_parameter< double >::type beta_s(beta_sSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cTF(cTFSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sTF(sTFSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type gwg_reps(gwg_repsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type chain_length(chain_lengthSEXP);
    __result = Rcpp::wrap(Gibbs_4PNO(Y, mu_xi, Sigma_xi_inv, mu_theta, Sigma_theta_inv, alpha_c, beta_c, alpha_s, beta_s, burnin, cTF, sTF, gwg_reps, chain_length));
    return __result;
END_RCPP
}
// update_2pno
Rcpp::List update_2pno(unsigned int N, unsigned int J, const arma::mat& Y, arma::mat& Z, const arma::vec& as, const arma::vec& bs, const arma::vec& theta, const arma::mat& Kaps, const arma::vec& mu_xi, const arma::mat& Sigma_xi_inv, const double& mu_theta, const double& Sigma_theta_inv);
RcppExport SEXP fourPNO_update_2pno(SEXP NSEXP, SEXP JSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP asSEXP, SEXP bsSEXP, SEXP thetaSEXP, SEXP KapsSEXP, SEXP mu_xiSEXP, SEXP Sigma_xi_invSEXP, SEXP mu_thetaSEXP, SEXP Sigma_theta_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type N(NSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type as(asSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kaps(KapsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_xi(mu_xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_xi_inv(Sigma_xi_invSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu_theta(mu_thetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type Sigma_theta_inv(Sigma_theta_invSEXP);
    __result = Rcpp::wrap(update_2pno(N, J, Y, Z, as, bs, theta, Kaps, mu_xi, Sigma_xi_inv, mu_theta, Sigma_theta_inv));
    return __result;
END_RCPP
}
// Gibbs_2PNO
Rcpp::List Gibbs_2PNO(const arma::mat& Y, const arma::vec& mu_xi, const arma::mat& Sigma_xi_inv, const double& mu_theta, const double& Sigma_theta_inv, unsigned int burnin, unsigned int chain_length);
RcppExport SEXP fourPNO_Gibbs_2PNO(SEXP YSEXP, SEXP mu_xiSEXP, SEXP Sigma_xi_invSEXP, SEXP mu_thetaSEXP, SEXP Sigma_theta_invSEXP, SEXP burninSEXP, SEXP chain_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_xi(mu_xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_xi_inv(Sigma_xi_invSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu_theta(mu_thetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type Sigma_theta_inv(Sigma_theta_invSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type chain_length(chain_lengthSEXP);
    __result = Rcpp::wrap(Gibbs_2PNO(Y, mu_xi, Sigma_xi_inv, mu_theta, Sigma_theta_inv, burnin, chain_length));
    return __result;
END_RCPP
}
